/**
 * Rota's world: every country on the map, where its middle sits on the
 * 1000×500 equirectangular map (app/lib/rota-map.ts), and what it borders.
 * Borders come from Natural Earth 1:110m (world-atlas); a few short sea
 * crossings (the Channel, Gibraltar, the Øresund…) are added so islands join in.
 * French Guiana is left out of France: its borders would link Europe to Brazil.
 */
export const ROTA_COUNTRIES: Record<string, { x: number; y: number; borders: string[] }> = {
  "Afghanistan": { x: 683.6, y: 156, borders: ["China","Iran","Pakistan","Tajikistan","Turkmenistan","Uzbekistan"] },
  "Albania": { x: 555.6, y: 135.7, borders: ["Greece","Italy","Kosovo","Montenegro","North Macedonia"] },
  "Algeria": { x: 507.2, y: 171.7, borders: ["Libya","Mali","Mauritania","Morocco","Niger","Tunisia","Western Sahara"] },
  "Angola": { x: 548.5, y: 284, borders: ["Congo","DR Congo","Namibia","Zambia"] },
  "Argentina": { x: 319, y: 348.5, borders: ["Bolivia","Brazil","Chile","Paraguay","Uruguay"] },
  "Armenia": { x: 625, y: 138.3, borders: ["Azerbaijan","Georgia","Iran","Turkey"] },
  "Australia": { x: 873.6, y: 321.5, borders: ["Indonesia","New Zealand","Papua New Guinea"] },
  "Austria": { x: 539.1, y: 117.7, borders: ["Czechia","Germany","Hungary","Italy","Slovakia","Slovenia","Switzerland"] },
  "Azerbaijan": { x: 632.1, y: 138.3, borders: ["Armenia","Georgia","Iran","Russia"] },
  "Bahamas": { x: 283.5, y: 179.1, borders: ["United States"] },
  "Bangladesh": { x: 750.7, y: 183.8, borders: ["India","Myanmar"] },
  "Belarus": { x: 577.7, y: 101.4, borders: ["Latvia","Lithuania","Poland","Russia","Ukraine"] },
  "Belgium": { x: 512.7, y: 109.3, borders: ["France","Germany","Luxembourg","Netherlands"] },
  "Belize": { x: 253.6, y: 202.2, borders: ["Guatemala","Mexico"] },
  "Benin": { x: 506.5, y: 223.2, borders: ["Burkina Faso","Niger","Nigeria","Togo"] },
  "Bhutan": { x: 751.3, y: 173.8, borders: ["China","India"] },
  "Bolivia": { x: 320.4, y: 296.5, borders: ["Argentina","Brazil","Chile","Paraguay","Peru"] },
  "Bosnia and Herzegovina": { x: 549.5, y: 127.3, borders: ["Croatia","Montenegro","Serbia"] },
  "Botswana": { x: 566, y: 311.4, borders: ["Namibia","South Africa","Zambia","Zimbabwe"] },
  "Brazil": { x: 352.6, y: 280, borders: ["Argentina","Bolivia","Colombia","Guyana","Paraguay","Peru","Suriname","Uruguay","Venezuela"] },
  "Brunei": { x: 819.2, y: 237, borders: ["Malaysia"] },
  "Bulgaria": { x: 570, y: 131.2, borders: ["Greece","North Macedonia","Romania","Serbia","Turkey"] },
  "Burkina Faso": { x: 495.1, y: 215.8, borders: ["Benin","Ghana","Ivory Coast","Mali","Niger","Togo"] },
  "Burundi": { x: 583.1, y: 259.4, borders: ["DR Congo","Rwanda","Tanzania"] },
  "Cambodia": { x: 791.3, y: 214.8, borders: ["Laos","Thailand","Vietnam"] },
  "Cameroon": { x: 535, y: 234.3, borders: ["Central African Republic","Chad","Congo","Equatorial Guinea","Gabon","Niger","Nigeria"] },
  "Canada": { x: 227.4, y: 79.3, borders: ["United States"] },
  "Central African Republic": { x: 556.6, y: 231.8, borders: ["Cameroon","Chad","Congo","DR Congo","South Sudan","Sudan"] },
  "Chad": { x: 551.6, y: 207.4, borders: ["Cameroon","Central African Republic","Libya","Niger","Sudan"] },
  "Chile": { x: 301.3, y: 358.5, borders: ["Argentina","Bolivia","Peru"] },
  "China": { x: 788.6, y: 148.5, borders: ["Afghanistan","Bhutan","India","Kazakhstan","Kyrgyzstan","Laos","Mongolia","Myanmar","Nepal","North Korea","Pakistan","Russia","Taiwan","Tajikistan","Vietnam"] },
  "Colombia": { x: 297, y: 239.1, borders: ["Brazil","Ecuador","Panama","Peru","Venezuela"] },
  "Congo": { x: 542, y: 252.3, borders: ["Angola","Cameroon","Central African Republic","DR Congo","Gabon"] },
  "Costa Rica": { x: 266.2, y: 222.3, borders: ["Nicaragua","Panama"] },
  "Croatia": { x: 546, y: 125, borders: ["Bosnia and Herzegovina","Hungary","Montenegro","Serbia","Slovenia"] },
  "Cuba": { x: 280.7, y: 189.9, borders: ["Haiti","Jamaica","United States"] },
  "Cyprus": { x: 591.8, y: 153, borders: ["Turkey"] },
  "Czechia": { x: 542.6, y: 111.7, borders: ["Austria","Germany","Poland","Slovakia"] },
  "DR Congo": { x: 565.5, y: 257.9, borders: ["Angola","Burundi","Central African Republic","Congo","Rwanda","South Sudan","Tanzania","Uganda","Zambia"] },
  "Denmark": { x: 527.4, y: 94.3, borders: ["Germany","Norway","Sweden"] },
  "Djibouti": { x: 618, y: 217.3, borders: ["Eritrea","Ethiopia","Somalia","Yemen"] },
  "Dominican Republic": { x: 304.3, y: 197.5, borders: ["Haiti","Puerto Rico"] },
  "Ecuador": { x: 282.3, y: 254, borders: ["Colombia","Peru"] },
  "Egypt": { x: 582.9, y: 176.4, borders: ["Israel","Libya","Saudi Arabia","Sudan"] },
  "El Salvador": { x: 253.1, y: 211.9, borders: ["Guatemala","Honduras"] },
  "Equatorial Guinea": { x: 528.8, y: 245.4, borders: ["Cameroon","Gabon"] },
  "Eritrea": { x: 607.4, y: 207.1, borders: ["Djibouti","Ethiopia","Sudan","Yemen"] },
  "Estonia": { x: 571.7, y: 87.1, borders: ["Finland","Latvia","Russia"] },
  "Eswatini": { x: 587.2, y: 323.6, borders: ["Mozambique","South Africa"] },
  "Ethiopia": { x: 609.9, y: 226, borders: ["Djibouti","Eritrea","Kenya","Somalia","South Sudan","Sudan"] },
  "Falkland Islands": { x: 334.9, y: 393.6, borders: [] },
  "Fiji": { x: 955.3, y: 298.1, borders: [] },
  "Finland": { x: 572.8, y: 70.8, borders: ["Estonia","Norway","Russia","Sweden"] },
  "France": { x: 506, y: 121, borders: ["Belgium","Germany","Italy","Luxembourg","Spain","Switzerland","United Kingdom"] },
  "Gabon": { x: 532.5, y: 251.8, borders: ["Cameroon","Congo","Equatorial Guinea"] },
  "Gambia": { x: 457.1, y: 212.6, borders: ["Senegal"] },
  "Georgia": { x: 620.8, y: 132.9, borders: ["Armenia","Azerbaijan","Russia","Turkey"] },
  "Germany": { x: 528.6, y: 108, borders: ["Austria","Belgium","Czechia","Denmark","France","Luxembourg","Netherlands","Poland","Switzerland"] },
  "Ghana": { x: 496.6, y: 228, borders: ["Burkina Faso","Ivory Coast","Togo"] },
  "Greece": { x: 563.1, y: 141.5, borders: ["Albania","Bulgaria","Italy","North Macedonia","Turkey"] },
  "Greenland": { x: 384.7, y: 42.3, borders: [] },
  "Guatemala": { x: 249, y: 206.4, borders: ["Belize","El Salvador","Honduras","Mexico"] },
  "Guinea": { x: 469.3, y: 221, borders: ["Guinea-Bissau","Ivory Coast","Liberia","Mali","Senegal","Sierra Leone"] },
  "Guinea-Bissau": { x: 458, y: 216.6, borders: ["Guinea","Senegal"] },
  "Guyana": { x: 336.2, y: 236.7, borders: ["Brazil","Suriname","Venezuela"] },
  "Haiti": { x: 298.2, y: 197.5, borders: ["Cuba","Dominican Republic"] },
  "Honduras": { x: 259.5, y: 208.8, borders: ["El Salvador","Guatemala","Nicaragua"] },
  "Hungary": { x: 553.8, y: 118.9, borders: ["Austria","Croatia","Romania","Serbia","Slovakia","Slovenia","Ukraine"] },
  "Iceland": { x: 447.9, y: 69.2, borders: ["United Kingdom"] },
  "India": { x: 721.1, y: 186.3, borders: ["Bangladesh","Bhutan","China","Myanmar","Nepal","Pakistan","Sri Lanka"] },
  "Indonesia": { x: 826.2, y: 256.2, borders: ["Australia","Malaysia","Papua New Guinea","Philippines","Timor-Leste"] },
  "Iran": { x: 650.8, y: 159.7, borders: ["Afghanistan","Armenia","Azerbaijan","Iraq","Oman","Pakistan","Turkey","Turkmenistan","United Arab Emirates"] },
  "Iraq": { x: 621.5, y: 158.2, borders: ["Iran","Jordan","Kuwait","Saudi Arabia","Syria","Turkey"] },
  "Ireland": { x: 477.7, y: 102.3, borders: ["United Kingdom"] },
  "Israel": { x: 597.2, y: 162.5, borders: ["Egypt","Jordan","Lebanon","Palestine","Syria"] },
  "Italy": { x: 533.7, y: 131.2, borders: ["Albania","Austria","France","Greece","Slovenia","Switzerland","Tunisia"] },
  "Ivory Coast": { x: 484.4, y: 229, borders: ["Burkina Faso","Ghana","Guinea","Liberia","Mali"] },
  "Jamaica": { x: 285.2, y: 199.6, borders: ["Cuba"] },
  "Japan": { x: 883.5, y: 145.4, borders: ["Russia","South Korea"] },
  "Jordan": { x: 602.2, y: 163.2, borders: ["Iraq","Israel","Palestine","Saudi Arabia","Syria"] },
  "Kazakhstan": { x: 686.9, y: 116.1, borders: ["China","Kyrgyzstan","Russia","Turkmenistan","Uzbekistan"] },
  "Kenya": { x: 605, y: 248.3, borders: ["Ethiopia","Somalia","South Sudan","Tanzania","Uganda"] },
  "Kosovo": { x: 558, y: 131.7, borders: ["Albania","Montenegro","North Macedonia","Serbia"] },
  "Kuwait": { x: 632.2, y: 168.6, borders: ["Iraq","Saudi Arabia"] },
  "Kyrgyzstan": { x: 707.3, y: 134.7, borders: ["China","Kazakhstan","Tajikistan","Uzbekistan"] },
  "Laos": { x: 788.2, y: 198.8, borders: ["Cambodia","China","Myanmar","Thailand","Vietnam"] },
  "Latvia": { x: 569, y: 92.2, borders: ["Belarus","Estonia","Lithuania","Russia"] },
  "Lebanon": { x: 599.6, y: 155.8, borders: ["Israel","Syria"] },
  "Lesotho": { x: 578.2, y: 332.3, borders: ["South Africa"] },
  "Liberia": { x: 473.9, y: 232.1, borders: ["Guinea","Ivory Coast","Sierra Leone"] },
  "Libya": { x: 549.9, y: 175, borders: ["Algeria","Chad","Egypt","Niger","Sudan","Tunisia"] },
  "Lithuania": { x: 566.3, y: 96.4, borders: ["Belarus","Latvia","Poland","Russia"] },
  "Luxembourg": { x: 516.6, y: 111.8, borders: ["Belgium","France","Germany"] },
  "Madagascar": { x: 629.7, y: 303.8, borders: ["Mozambique"] },
  "Malawi": { x: 595, y: 286.6, borders: ["Mozambique","Tanzania","Zambia"] },
  "Malaysia": { x: 804.7, y: 239.7, borders: ["Brunei","Indonesia","Philippines","Thailand"] },
  "Mali": { x: 490.2, y: 202, borders: ["Algeria","Burkina Faso","Guinea","Ivory Coast","Mauritania","Niger","Senegal"] },
  "Mauritania": { x: 471.3, y: 193.9, borders: ["Algeria","Mali","Senegal","Western Sahara"] },
  "Mexico": { x: 215.1, y: 183.5, borders: ["Belize","Guatemala","United States"] },
  "Moldova": { x: 578.9, y: 118.9, borders: ["Romania","Ukraine"] },
  "Mongolia": { x: 786, y: 119.9, borders: ["China","Russia"] },
  "Montenegro": { x: 553.6, y: 131.1, borders: ["Albania","Bosnia and Herzegovina","Croatia","Kosovo","Serbia"] },
  "Morocco": { x: 476.6, y: 167, borders: ["Algeria","Spain","Western Sahara"] },
  "Mozambique": { x: 598.5, y: 297.9, borders: ["Eswatini","Madagascar","Malawi","South Africa","Tanzania","Zambia","Zimbabwe"] },
  "Myanmar": { x: 768.1, y: 191.6, borders: ["Bangladesh","China","India","Laos","Thailand"] },
  "Namibia": { x: 547.7, y: 311.4, borders: ["Angola","Botswana","South Africa","Zambia"] },
  "Nepal": { x: 733.4, y: 171.6, borders: ["China","India"] },
  "Netherlands": { x: 515.3, y: 104.7, borders: ["Belgium","Germany"] },
  "New Caledonia": { x: 959.8, y: 309.1, borders: [] },
  "New Zealand": { x: 979.7, y: 365.7, borders: ["Australia"] },
  "Nicaragua": { x: 263.8, y: 214.3, borders: ["Costa Rica","Honduras"] },
  "Niger": { x: 525.9, y: 201.8, borders: ["Algeria","Benin","Burkina Faso","Cameroon","Chad","Libya","Mali","Nigeria"] },
  "Nigeria": { x: 522.2, y: 223.5, borders: ["Benin","Cameroon","Niger"] },
  "North Korea": { x: 853.2, y: 138.5, borders: ["China","North Korea","Russia","South Korea"] },
  "North Macedonia": { x: 560.3, y: 134.4, borders: ["Albania","Bulgaria","Greece","Kosovo","Serbia"] },
  "Norway": { x: 543, y: 57.9, borders: ["Denmark","Finland","Russia","Sweden"] },
  "Oman": { x: 655.8, y: 192.7, borders: ["Iran","Saudi Arabia","United Arab Emirates","Yemen"] },
  "Pakistan": { x: 692.8, y: 166.7, borders: ["Afghanistan","China","India","Iran"] },
  "Palestine": { x: 598, y: 161.3, borders: ["Israel","Jordan"] },
  "Panama": { x: 277.5, y: 226.3, borders: ["Colombia","Costa Rica"] },
  "Papua New Guinea": { x: 903.7, y: 267.9, borders: ["Australia","Indonesia"] },
  "Paraguay": { x: 337.8, y: 314.6, borders: ["Argentina","Bolivia","Brazil"] },
  "Peru": { x: 293.4, y: 275.5, borders: ["Bolivia","Brazil","Chile","Colombia","Ecuador"] },
  "Philippines": { x: 841.4, y: 217.3, borders: ["Indonesia","Malaysia"] },
  "Poland": { x: 553.6, y: 105.1, borders: ["Belarus","Czechia","Germany","Lithuania","Russia","Slovakia","Ukraine"] },
  "Portugal": { x: 477.6, y: 139.9, borders: ["Spain"] },
  "Puerto Rico": { x: 315.3, y: 199.3, borders: ["Dominican Republic"] },
  "Qatar": { x: 642.2, y: 179.7, borders: ["Saudi Arabia"] },
  "Romania": { x: 569.3, y: 122.6, borders: ["Bulgaria","Hungary","Moldova","Serbia","Ukraine"] },
  "Russia": { x: 769.1, y: 77.8, borders: ["Azerbaijan","Belarus","China","Estonia","Finland","Georgia","Japan","Kazakhstan","Latvia","Lithuania","Mongolia","North Korea","Norway","Poland","Ukraine","United States"] },
  "Rwanda": { x: 583.1, y: 255.6, borders: ["Burundi","DR Congo","Tanzania","Uganda"] },
  "Saudi Arabia": { x: 623.7, y: 183, borders: ["Egypt","Iraq","Jordan","Kuwait","Oman","Qatar","United Arab Emirates","Yemen"] },
  "Senegal": { x: 459.7, y: 210.1, borders: ["Gambia","Guinea","Guinea-Bissau","Mali","Mauritania"] },
  "Serbia": { x: 557.8, y: 127.1, borders: ["Bosnia and Herzegovina","Bulgaria","Croatia","Hungary","Kosovo","Montenegro","North Macedonia","Romania"] },
  "Sierra Leone": { x: 467.2, y: 226.3, borders: ["Guinea","Liberia"] },
  "Slovakia": { x: 554.2, y: 114.6, borders: ["Austria","Czechia","Hungary","Poland","Ukraine"] },
  "Slovenia": { x: 541.5, y: 121.9, borders: ["Austria","Croatia","Hungary","Italy"] },
  "Solomon Islands": { x: 944.4, y: 274.6, borders: [] },
  "Somalia": { x: 627, y: 236.8, borders: ["Djibouti","Ethiopia","Kenya"] },
  "South Africa": { x: 569.6, y: 330.4, borders: ["Botswana","Eswatini","Lesotho","Mozambique","Namibia","Zimbabwe"] },
  "South Korea": { x: 855.1, y: 148.8, borders: ["Japan","North Korea"] },
  "South Sudan": { x: 583.9, y: 229.7, borders: ["Central African Republic","DR Congo","Ethiopia","Kenya","Sudan","Uganda"] },
  "Spain": { x: 490, y: 137.9, borders: ["France","Morocco","Portugal"] },
  "Sri Lanka": { x: 724.1, y: 228.6, borders: ["India"] },
  "Sudan": { x: 583, y: 205.6, borders: ["Central African Republic","Chad","Egypt","Eritrea","Ethiopia","Libya","South Sudan"] },
  "Suriname": { x: 344.7, y: 238.6, borders: ["Brazil","Guyana"] },
  "Sweden": { x: 546.1, y: 75.5, borders: ["Denmark","Finland","Norway"] },
  "Switzerland": { x: 522.6, y: 120, borders: ["Austria","France","Germany","Italy"] },
  "Syria": { x: 607.1, y: 152.7, borders: ["Iraq","Israel","Jordan","Lebanon","Turkey"] },
  "Taiwan": { x: 836, y: 184.1, borders: ["China"] },
  "Tajikistan": { x: 697.3, y: 142.8, borders: ["Afghanistan","China","Kyrgyzstan","Uzbekistan"] },
  "Tanzania": { x: 596.5, y: 267.4, borders: ["Burundi","DR Congo","Kenya","Malawi","Mozambique","Rwanda","Uganda","Zambia"] },
  "Thailand": { x: 780.6, y: 208.3, borders: ["Cambodia","Laos","Malaysia","Myanmar"] },
  "Timor-Leste": { x: 849.9, y: 274.4, borders: ["Indonesia"] },
  "Togo": { x: 502.8, y: 226.6, borders: ["Benin","Burkina Faso","Ghana"] },
  "Trinidad and Tobago": { x: 329.6, y: 221, borders: ["Venezuela"] },
  "Tunisia": { x: 526.5, y: 155.1, borders: ["Algeria","Italy","Libya"] },
  "Turkey": { x: 597.5, y: 141.5, borders: ["Armenia","Bulgaria","Cyprus","Georgia","Greece","Iran","Iraq","Syria"] },
  "Turkmenistan": { x: 664.7, y: 141.4, borders: ["Afghanistan","Iran","Kazakhstan","Uzbekistan"] },
  "Uganda": { x: 589.9, y: 246.4, borders: ["DR Congo","Kenya","Rwanda","South Sudan","Tanzania"] },
  "Ukraine": { x: 587.1, y: 114, borders: ["Belarus","Hungary","Moldova","Poland","Romania","Russia","Slovakia"] },
  "United Arab Emirates": { x: 650.6, y: 183.7, borders: ["Iran","Oman","Saudi Arabia"] },
  "United Kingdom": { x: 492.1, y: 100.2, borders: ["France","Iceland","Ireland"] },
  "United States": { x: 187.2, y: 123, borders: ["Bahamas","Canada","Cuba","Mexico","Russia"] },
  "Uruguay": { x: 344.4, y: 341.1, borders: ["Argentina","Brazil"] },
  "Uzbekistan": { x: 675.6, y: 134, borders: ["Afghanistan","Kazakhstan","Kyrgyzstan","Tajikistan","Turkmenistan"] },
  "Vanuatu": { x: 964.1, y: 293.2, borders: [] },
  "Venezuela": { x: 316.2, y: 230.1, borders: ["Brazil","Colombia","Guyana","Trinidad and Tobago"] },
  "Vietnam": { x: 795.2, y: 203.7, borders: ["Cambodia","China","Laos"] },
  "Western Sahara": { x: 466.3, y: 182.5, borders: ["Algeria","Mauritania","Morocco"] },
  "Yemen": { x: 632, y: 205.8, borders: ["Djibouti","Eritrea","Oman","Saudi Arabia"] },
  "Zambia": { x: 577, y: 287.2, borders: ["Angola","Botswana","DR Congo","Malawi","Mozambique","Namibia","Tanzania","Zimbabwe"] },
  "Zimbabwe": { x: 582.7, y: 302.5, borders: ["Botswana","Mozambique","South Africa","Zambia"] },
};

/** Turkish names for every country on the map. */
export const ROTA_TR: Record<string, string> = {
  "Afghanistan": "Afganistan",
  "Albania": "Arnavutluk",
  "Algeria": "Cezayir",
  "Angola": "Angola",
  "Argentina": "Arjantin",
  "Armenia": "Ermenistan",
  "Australia": "Avustralya",
  "Austria": "Avusturya",
  "Azerbaijan": "Azerbaycan",
  "Bahamas": "Bahamalar",
  "Bangladesh": "Bangladeş",
  "Belarus": "Beyaz Rusya",
  "Belgium": "Belçika",
  "Belize": "Belize",
  "Benin": "Benin",
  "Bhutan": "Butan",
  "Bolivia": "Bolivya",
  "Bosnia and Herzegovina": "Bosna Hersek",
  "Botswana": "Botsvana",
  "Brazil": "Brezilya",
  "Brunei": "Brunei",
  "Bulgaria": "Bulgaristan",
  "Burkina Faso": "Burkina Faso",
  "Burundi": "Burundi",
  "Cambodia": "Kamboçya",
  "Cameroon": "Kamerun",
  "Canada": "Kanada",
  "Central African Republic": "Orta Afrika Cumhuriyeti",
  "Chad": "Çad",
  "Chile": "Şili",
  "China": "Çin",
  "Colombia": "Kolombiya",
  "Congo": "Kongo",
  "Costa Rica": "Kosta Rika",
  "Croatia": "Hırvatistan",
  "Cuba": "Küba",
  "Cyprus": "Kıbrıs",
  "Czechia": "Çekya",
  "DR Congo": "Demokratik Kongo Cumhuriyeti",
  "Denmark": "Danimarka",
  "Djibouti": "Cibuti",
  "Dominican Republic": "Dominik Cumhuriyeti",
  "Ecuador": "Ekvador",
  "Egypt": "Mısır",
  "El Salvador": "El Salvador",
  "Equatorial Guinea": "Ekvator Ginesi",
  "Eritrea": "Eritre",
  "Estonia": "Estonya",
  "Eswatini": "Esvatini",
  "Ethiopia": "Etiyopya",
  "Falkland Islands": "Falkland Adaları",
  "Fiji": "Fiji",
  "Finland": "Finlandiya",
  "France": "Fransa",
  "Gabon": "Gabon",
  "Gambia": "Gambiya",
  "Georgia": "Gürcistan",
  "Germany": "Almanya",
  "Ghana": "Gana",
  "Greece": "Yunanistan",
  "Greenland": "Grönland",
  "Guatemala": "Guatemala",
  "Guinea": "Gine",
  "Guinea-Bissau": "Gine-Bissau",
  "Guyana": "Guyana",
  "Haiti": "Haiti",
  "Honduras": "Honduras",
  "Hungary": "Macaristan",
  "Iceland": "İzlanda",
  "India": "Hindistan",
  "Indonesia": "Endonezya",
  "Iran": "İran",
  "Iraq": "Irak",
  "Ireland": "İrlanda",
  "Israel": "İsrail",
  "Italy": "İtalya",
  "Ivory Coast": "Fildişi Sahili",
  "Jamaica": "Jamaika",
  "Japan": "Japonya",
  "Jordan": "Ürdün",
  "Kazakhstan": "Kazakistan",
  "Kenya": "Kenya",
  "Kosovo": "Kosova",
  "Kuwait": "Kuveyt",
  "Kyrgyzstan": "Kırgızistan",
  "Laos": "Laos",
  "Latvia": "Letonya",
  "Lebanon": "Lübnan",
  "Lesotho": "Lesoto",
  "Liberia": "Liberya",
  "Libya": "Libya",
  "Lithuania": "Litvanya",
  "Luxembourg": "Lüksemburg",
  "Madagascar": "Madagaskar",
  "Malawi": "Malavi",
  "Malaysia": "Malezya",
  "Mali": "Mali",
  "Mauritania": "Moritanya",
  "Mexico": "Meksika",
  "Moldova": "Moldova",
  "Mongolia": "Moğolistan",
  "Montenegro": "Karadağ",
  "Morocco": "Fas",
  "Mozambique": "Mozambik",
  "Myanmar": "Myanmar",
  "Namibia": "Namibya",
  "Nepal": "Nepal",
  "Netherlands": "Hollanda",
  "New Caledonia": "Yeni Kaledonya",
  "New Zealand": "Yeni Zelanda",
  "Nicaragua": "Nikaragua",
  "Niger": "Nijer",
  "Nigeria": "Nijerya",
  "North Korea": "Kuzey Kore",
  "North Macedonia": "Kuzey Makedonya",
  "Norway": "Norveç",
  "Oman": "Umman",
  "Pakistan": "Pakistan",
  "Palestine": "Filistin",
  "Panama": "Panama",
  "Papua New Guinea": "Papua Yeni Gine",
  "Paraguay": "Paraguay",
  "Peru": "Peru",
  "Philippines": "Filipinler",
  "Poland": "Polonya",
  "Portugal": "Portekiz",
  "Puerto Rico": "Porto Riko",
  "Qatar": "Katar",
  "Romania": "Romanya",
  "Russia": "Rusya",
  "Rwanda": "Ruanda",
  "Saudi Arabia": "Suudi Arabistan",
  "Senegal": "Senegal",
  "Serbia": "Sırbistan",
  "Sierra Leone": "Sierra Leone",
  "Slovakia": "Slovakya",
  "Slovenia": "Slovenya",
  "Solomon Islands": "Solomon Adaları",
  "Somalia": "Somali",
  "South Africa": "Güney Afrika",
  "South Korea": "Güney Kore",
  "South Sudan": "Güney Sudan",
  "Spain": "İspanya",
  "Sri Lanka": "Sri Lanka",
  "Sudan": "Sudan",
  "Suriname": "Surinam",
  "Sweden": "İsveç",
  "Switzerland": "İsviçre",
  "Syria": "Suriye",
  "Taiwan": "Tayvan",
  "Tajikistan": "Tacikistan",
  "Tanzania": "Tanzanya",
  "Thailand": "Tayland",
  "Timor-Leste": "Timor-Leste",
  "Togo": "Togo",
  "Trinidad and Tobago": "Trinidad ve Tobago",
  "Tunisia": "Tunus",
  "Turkey": "Türkiye",
  "Turkmenistan": "Türkmenistan",
  "Uganda": "Uganda",
  "Ukraine": "Ukrayna",
  "United Arab Emirates": "Birleşik Arap Emirlikleri",
  "United Kingdom": "Birleşik Krallık",
  "United States": "Amerika Birleşik Devletleri",
  "Uruguay": "Uruguay",
  "Uzbekistan": "Özbekistan",
  "Vanuatu": "Vanuatu",
  "Venezuela": "Venezuela",
  "Vietnam": "Vietnam",
  "Western Sahara": "Batı Sahara",
  "Yemen": "Yemen",
  "Zambia": "Zambiya",
  "Zimbabwe": "Zimbabve",
};

/** The sea crossings among ROTA_COUNTRIES' borders, drawn on the map so they can be seen. */
export const ROTA_SEA: Array<[string, string]> = [
  ["United Kingdom", "France"], ["Denmark", "Sweden"], ["Spain", "Morocco"], ["Somalia", "Djibouti"], ["India", "Sri Lanka"], ["Japan", "South Korea"], ["Italy", "Tunisia"], ["Egypt", "Saudi Arabia"], ["Australia", "Papua New Guinea"], ["Indonesia", "Australia"], ["Cyprus", "Turkey"], ["Iceland", "United Kingdom"], ["Madagascar", "Mozambique"], ["Philippines", "Malaysia"], ["Taiwan", "China"], ["Cuba", "United States"], ["Haiti", "Cuba"], ["Jamaica", "Cuba"], ["Trinidad and Tobago", "Venezuela"], ["Sweden", "Finland"], ["Estonia", "Finland"], ["Yemen", "Djibouti"], ["New Zealand", "Australia"], ["Bahamas", "United States"], ["Puerto Rico", "Dominican Republic"],
  ["Greece","Italy"],
  ["Albania","Italy"],
  ["Yemen","Eritrea"],
  ["Iran","Oman"],
  ["Iran","United Arab Emirates"],
  ["Russia","Japan"],
  ["Denmark","Norway"],
  ["Indonesia","Philippines"],
  ["Russia","United States"],
];

/**
 * Where a sea crossing meets each shore, for crossings whose countries' middles
 * are far from the strait. Keyed "A|B" in ROTA_SEA's order.
 */
export const ROTA_SEA_ENDS: Record<string, [{ x: number; y: number }, { x: number; y: number }]> = {
  // The Bering Strait: Chukotka and Alaska, either side of the date line.
  "Russia|United States": [{ x: 987, y: 66 }, { x: 30, y: 68 }],
};
