#!/bin/sh
# Container entrypoint for Hoffle.
#
# Builds the env file wrangler hands to the worker, then starts the server.
# Settings come from three places, and later ones win:
#
#   1. /app/state/secrets.env  generated on first boot (BOT_TOKEN, BOOTSTRAP_CODE)
#   2. /app/.dev.vars          optional mounted file (older setups used this)
#   3. container environment   what docker compose passes in from .env
#
# Wrangler does not forward the process environment to the worker, so a
# variable only takes effect if it is listed in PASSTHROUGH_KEYS below.
set -e

STATE_DIR="${PERSIST_DIR:-/app/state}"
SECRETS_FILE="$STATE_DIR/secrets.env"
RUNTIME_ENV="/tmp/hoffle.env"

PASSTHROUGH_KEYS="
BASE_PATH
BOOTSTRAP_CODE
BOT_TOKEN
DND_BASE_URL
DND_PUBLIC_URL
FEATURE_RECORD_SESSIONS
GOOGLE_SITE_VERIFICATION
HUDDLE_ICE_SERVERS
KLIPY_API_KEY
LANDING_DOMAINS
LASTFM_API_KEY
LASTFM_SECRET
LIVEKIT_API_KEY
LIVEKIT_API_SECRET
LIVEKIT_URL
MUSICWATCH_BASE_URL
MUSICWATCH_PASSWORD
MUSICWATCH_PUBLIC_URL
MUSIC_HELPER_BASE_URL
NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION
RECORDER_SERVICE_TOKEN
RECORDER_SERVICE_URL
VAPID_PRIVATE_KEY
VAPID_PUBLIC_KEY
VAPID_SUBJECT
"

random_string() {
  # $1 = allowed characters, $2 = length
  tr -dc "$1" < /dev/urandom | head -c "$2"
}

mkdir -p "$STATE_DIR"

# --- 1. First-boot secrets ---------------------------------------------------
if [ ! -f "$SECRETS_FILE" ]; then
  echo "First start: generating secrets in $SECRETS_FILE"
  umask 077
  {
    echo "# Generated by Hoffle on first start. Anything set in .env overrides these."
    echo "BOT_TOKEN=$(random_string 'a-zA-Z0-9' 40)"
    echo "BOOTSTRAP_CODE=$(random_string 'A-HJ-NP-Z2-9' 10)"
  } > "$SECRETS_FILE"
  umask 022
fi

# --- 2 & 3. Merge into the runtime env file ----------------------------------
: > "$RUNTIME_ENV"
chmod 600 "$RUNTIME_ENV"
grep -E '^[A-Z_][A-Z0-9_]*=' "$SECRETS_FILE" >> "$RUNTIME_ENV" || true
if [ -f /app/.dev.vars ]; then
  grep -E '^[A-Z_][A-Z0-9_]*=' /app/.dev.vars >> "$RUNTIME_ENV" || true
fi
for key in $PASSTHROUGH_KEYS; do
  value="$(printenv "$key" || true)"
  if [ -n "$value" ]; then
    # dotenv reads one line per key, so drop any stray newlines.
    printf '%s=%s\n' "$key" "$(printf '%s' "$value" | tr -d '\r\n')" >> "$RUNTIME_ENV"
  fi
done

# Keep only the last value for each key so the precedence above holds.
awk -F= '{ last[$1] = $0; if (!($1 in seen)) { seen[$1] = 1; order[++n] = $1 } }
  END { for (i = 1; i <= n; i++) print last[order[i]] }' "$RUNTIME_ENV" > "$RUNTIME_ENV.tmp"
mv "$RUNTIME_ENV.tmp" "$RUNTIME_ENV"

env_value() {
  grep -E "^$1=" "$RUNTIME_ENV" | tail -n 1 | cut -d= -f2-
}

# --- Welcome banner ----------------------------------------------------------
# The setup code is only useful until the first account exists, so it is shown
# while the users table is empty (or the database has not been created yet).
user_count() {
  for db in "$STATE_DIR"/v3/d1/miniflare-D1DatabaseObject/*.sqlite; do
    [ -f "$db" ] || continue
    case "$db" in */metadata.sqlite|*/backup-*) continue ;; esac
    count="$(sqlite3 "$db" 'SELECT COUNT(*) FROM users;' 2>/dev/null || true)"
    if [ -n "$count" ]; then
      echo "$count"
      return
    fi
  done
  echo 0
}

PUBLIC_PORT="${HOFFLE_PORT:-8730}"
if [ "$(user_count)" = "0" ]; then
  echo ""
  echo "  ================================================================"
  echo "   Hoffle is starting. Open it in your browser:"
  echo ""
  echo "     http://localhost:$PUBLIC_PORT"
  echo "     (or http://<this-machine's-ip>:$PUBLIC_PORT from another device)"
  echo ""
  echo "   Create the first account (it becomes the owner). When it asks"
  echo "   for a setup code, enter:"
  echo ""
  echo "     $(env_value BOOTSTRAP_CODE)"
  echo ""
  echo "   Print this again any time with:"
  echo "     docker exec hoffle cat /app/state/secrets.env"
  echo "  ================================================================"
  echo ""
fi

# --- Start -------------------------------------------------------------------
HELPER_PID=""
if [ "${HOFFLE_START_MUSIC_HELPER:-0}" = "1" ]; then
  echo "Starting music helper on 127.0.0.1:8731"
  HOST=127.0.0.1 PORT=8731 /app/pyenv/bin/python3 /app/huddle_music_helper.py &
  HELPER_PID=$!
fi

cleanup() {
  echo "Stopping Hoffle..."
  [ -n "$SERVER_PID" ] && kill -TERM "$SERVER_PID" 2>/dev/null || true
  [ -n "$HELPER_PID" ] && kill -TERM "$HELPER_PID" 2>/dev/null || true
  wait 2>/dev/null || true
  exit 0
}
trap cleanup INT TERM

echo "Starting Hoffle on port 8730"
npx wrangler dev \
  --config /app/dist/server/wrangler.json \
  --env-file "$RUNTIME_ENV" \
  --ip 0.0.0.0 \
  --port 8730 \
  --persist-to "$STATE_DIR" &
SERVER_PID=$!

wait "$SERVER_PID"
